### ISSUE TITLE
Syntax highlighting breaks for certain types of for loops

### ISSUE THREAD

**Issue by mrice32** [davidhq/SublimeEthereum#35]
For for loops that contain an `=` in the third statement, syntax parsing seems to break going forward. The following for loop would break, for example:
```
for (uint i = 0; i < n; i = i + 2) {
...
}
```

I've provided a screenshot as well.

![image](https://user-images.githubusercontent.com/11791551/53451944-04f9f300-39ee-11e9-9377-9c828ea1c872.png)

**Comment by davidhq** [comment]
Thank you very much for this report. Fixed in `1.1.10`. Please write back if you find any other issue.

**Comment by mrice32** [comment]
Thank you!

**Comment by AtlasQuan** [comment]
Still have the problem of loop.
It **doesn't work** when the code is like
```
for (i=1; i < n; i ++)
```
but it **works** when the code is like:
```
for (i = i; i < n; i++)
```
Is that as expected? I just feel really weird...
My Ethereum package version: v1.1.20, Sublime Text: v3.2.1
Screenshots attached:
![Screenshot from 2019-05-24 10-55-18](https://user-images.githubusercontent.com/17843377/58299673-83f6a000-7e12-11e9-885e-42593652e84a.png)
![Screenshot from 2019-05-24 10-55-32](https://user-images.githubusercontent.com/17843377/58299674-8658fa00-7e12-11e9-8fcb-7d23b65ff44b.png)

Thanks!

**Comment by davidhq** [comment]
Thank you very much for this.

I did two things in `v1.1.21` :

- fix an obvious issue with spaces around '=' as you noticed
- made an additional guard for when there are certain user errors (or even further highlighter issues) inside (...) so that the problem doesn't break the highlighting further down... on example where problem doesn't spread out of brackets anymore is this user typo: `for (strinfg i = 0; i < n; i++) {`

I hope this fix didn't break something else, I checked on example contracts and the highlighter code itself is of enough quality that this should not be the case but still - would be grateful for checks by others... as always, report if you still find something, will be fixed....

**Comment by AtlasQuan** [comment]
Thanks so much!
